googlemaps3test/config/routes.rb
Rails.application.routes.draw do
  resources :autocompletes
  root to: 'autocompletes#new'
end

googlemaps3test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

googlemaps3test/app/models/autocomplete.rb
class Autocomplete < ApplicationRecord
end

googlemaps3test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

googlemaps3test/app/controllers/autocompletes_controller.rb
class AutocompletesController < ApplicationController
  before_action :set_autocomplete, only: [:show, :edit, :update, :destroy]

  # GET /autocompletes
  # GET /autocompletes.json
  def index
    @autocompletes = Autocomplete.all
  end

  # GET /autocompletes/1
  # GET /autocompletes/1.json
  def show
  end

  # GET /autocompletes/new
  def new
    @autocomplete = Autocomplete.new
  end

  # GET /autocompletes/1/edit
  def edit
  end

  # POST /autocompletes
  # POST /autocompletes.json
  def create
    @autocomplete = Autocomplete.new(autocomplete_params)

    respond_to do |format|
      if @autocomplete.save
        format.html { redirect_to @autocomplete, notice: 'Autocomplete was successfully created.' }
        format.json { render :show, status: :created, location: @autocomplete }
      else
        format.html { render :new }
        format.json { render json: @autocomplete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autocompletes/1
  # PATCH/PUT /autocompletes/1.json
  def update
    respond_to do |format|
      if @autocomplete.update(autocomplete_params)
        format.html { redirect_to @autocomplete, notice: 'Autocomplete was successfully updated.' }
        format.json { render :show, status: :ok, location: @autocomplete }
      else
        format.html { render :edit }
        format.json { render json: @autocomplete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autocompletes/1
  # DELETE /autocompletes/1.json
  def destroy
    @autocomplete.destroy
    respond_to do |format|
      format.html { redirect_to autocompletes_url, notice: 'Autocomplete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autocomplete
      @autocomplete = Autocomplete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def autocomplete_params
      params.require(:autocomplete).permit(:address, :street_number, :locality, :route, :administrative_area_level_1, :country, :postal_code)
    end
end

googlemaps3test/app/helpers/autocompletes_helper.rb
module AutocompletesHelper
end

googlemaps3test/app/views/autocompletes/_form.html.erb
<%= form_with(model: autocomplete, local: true) do |form| %>
  <% if autocomplete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(autocomplete.errors.count, "error") %> prohibited this autocomplete from being saved:</h2>

      <ul>
      <% autocomplete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
 <%= form.label 'Adress' %>
 <%= form.text_field :address, placeholder: "Enter your adress", id: :autocomplete_address %>
</div>

<div class="field">
 <%= form.label 'Channel numberrrrrrrrrrr' %>
 <%= form.number_field :street_number, id: :street_number %>
</div>

<div class="field">
 <%= form.label 'Town' %>
 <%= form.text_field :locality, id: :locality %>
</div>
 
<div class="field">
 <%= form.label 'Name of the channel' %>
 <%= form.text_field :route, id: :route %>
</div>

<div class="field">
 <%= form.label 'Area' %>
 <%= form.text_field :administrative_area_level_1, id: :administrative_area_level_1 %>
</div>

<div class="field">
 <%= form.label 'Country' %>
 <%= form.text_field :country, id: :country %>
</div>

<div class="field">
 <%= form.label 'Postal code' %>
 <%= form.number_field :postal_code, id: :postal_code %>
</div>

<div class="actions">
 <div class="btn waves-effect waves-light">
  <%= form.submit "submit" %>
 </div>
</div>
<% end %>

googlemaps3test/app/views/autocompletes/edit.html.erb
<h1>Editing Autocomplete</h1>

<%= render 'form', autocomplete: @autocomplete %>

<%= link_to 'Show', @autocomplete %> |
<%= link_to 'Back', autocompletes_path %>

googlemaps3test/app/views/autocompletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Autocompletes</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Street number</th>
      <th>Locality</th>
      <th>Route</th>
      <th>Administrative area level 1</th>
      <th>Country</th>
      <th>Postal code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autocompletes.each do |autocomplete| %>
      <tr>
        <td><%= autocomplete.address %></td>
        <td><%= autocomplete.street_number %></td>
        <td><%= autocomplete.locality %></td>
        <td><%= autocomplete.route %></td>
        <td><%= autocomplete.administrative_area_level_1 %></td>
        <td><%= autocomplete.country %></td>
        <td><%= autocomplete.postal_code %></td>
        <td><%= link_to 'Show', autocomplete %></td>
        <td><%= link_to 'Edit', edit_autocomplete_path(autocomplete) %></td>
        <td><%= link_to 'Destroy', autocomplete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Autocomplete', new_autocomplete_path %>

googlemaps3test/app/views/autocompletes/new.html.erb
<div class="flexbox">   
 <h1>Autocomplete</h1>   
 <%= render 'form', autocomplete: @autocomplete %>
 <%= link_to 'Back', autocompletes_path %> 
</div> 

googlemaps3test/app/views/autocompletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @autocomplete.address %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @autocomplete.street_number %>
</p>

<p>
  <strong>Locality:</strong>
  <%= @autocomplete.locality %>
</p>

<p>
  <strong>Route:</strong>
  <%= @autocomplete.route %>
</p>

<p>
  <strong>Administrative area level 1:</strong>
  <%= @autocomplete.administrative_area_level_1 %>
</p>

<p>
  <strong>Country:</strong>
  <%= @autocomplete.country %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @autocomplete.postal_code %>
</p>

<%= link_to 'Edit', edit_autocomplete_path(@autocomplete) %> |
<%= link_to 'Back', autocompletes_path %>

googlemaps3test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html land="en-us">

<head>
    <title>Simple UI</title>
    <meta name="viewport" content="initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="application.scss">
    <script src="map.js"></script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDutuTXuuUC-5ywb9P6j4OOs7u_sliwfwM&callback=initMap">
    </script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
   <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="menu" id="menu">
        <div class="options">
            <nav>
                <button class="button bus" id = "bus" onclick="busButton()"><i class="fa fa-bus"></i></button>
                <button class="button bike" id = "bike" onclick="bikeButton()"><i class="fa fa-bicycle"></i></button>
                <button class="button walk" id = "walk" onclick="walkButton()"><i class="fa fa-blind"></i></button>
                <button class="button car" id = "car" onclick="carButton()"><i class="fa fa-car"></i></button>
                <button class="button wheelchair" id = "wheelchair" onclick="wheelchairButton()"><i class="fa fa-wheelchair-alt"></i></button>
                <div class="pretty p-icon p-round p-pulse" id = "VeoOption" style = "visibility: hidden">
                    <input type="checkbox" />
                    <div class="state p-primary">
                        <i class="icon mdi mdi-check"></i>
                        <label>Veoride</label>
                    </div>
                </div>
            </nav>
        </div>

        <input class = "currentLocation" id="currentLocation" onclick="firstbox()">
        <input class = "destination" id="destination" onclick="secondbox()">
        <button style = "visibility: visible;" class="Directions" id = "search1" onclick="Directions()"><i class="material-icons" style = "font-size: 30px; color: rgb(122, 0, 0);; position: absolute; right: 5px; top: 5px;">directions</i></button>
        <button style = "visibility: hidden;" class="Directions2" id = "search2" onclick="Directions()"><i class="material-icons" style = "font-size: 30px; color: rgb(122, 0, 0);; position: absolute; right: 5px; top: 5px;">directions</i></button>
        <div class="directions" id = "output"> </div>
    </div>

    <button class="menubtn" id="menubtn" onclick="openMenu()">
        <i class="fa fa-caret-right" style="font-size:24px"></i>
    </button>

    <div id="map"></div>

    <script src="buttons.js"></script>
</body>

</html>